name: Build EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # Cache Playwright (ACCELERE builds futurs)
    - name: Cache Playwright
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}

    - name: Install dependencies
      run: |
        pip install playwright pyinstaller
        python -m playwright install chromium

      env:
        PLAYWRIGHT_BROWSERS_PATH: 0

    # BUILD OPTIMISÉ (IMPORTANT)
    - name: Build EXE
      run: |
        pyinstaller --onedir --noconsole --clean main.py

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: exe
        path: dist/
