name: Build EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      PLAYWRIGHT_BROWSERS_PATH: 0

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install playwright pyinstaller bs4 requests openpyxl
        python -m playwright install chromium

    - name: Build EXE
      shell: pwsh
      run: >
        pyinstaller --onefile --noconsole
        --collect-all playwright
        --add-data "modules;modules"
        --add-data "Templates;Templates"
        main.py

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: exe
        path: dist/*.exe
